import { DataTypeEnum, IData } from '../interfaces/data.interfaces';

const data: Array<IData> = [
  {
    type: DataTypeEnum.Sentence,
    text: 'Em tinnav?',
    meaning: 'What did you eat?',
    pronunciation: 'em tee-nahv',
    examples: [
      'Em tinnav ninna? (What did you eat yesterday?)',
      'Morning em tinnav? (What did you eat in the morning?)',
      'Lunch lo em tinnav? (What did you eat for lunch?)',
      'Em tinnav annamata? (So what did you eat?)',
      'Nuvvu em tinnav? (What did you eat?)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Nuvvu',
    meaning: 'You',
    pronunciation: 'noo-voo',
    examples: [
      'Nuvvu ekkada unnav? (Where are you?)',
      'Nuvvu em chepthunnavu? (What are you saying?)',
      'Nuvvu nenu kaluddam (You and I will meet)',
      'Nuvvu evaru? (Who are you?)',
      'Nuvvu kavali (I need you)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Meeru',
    meaning: 'You (respectful, to address elders and all)',
    pronunciation: 'mee-roo',
    examples: [
      'Meeru ela unnaru? (How are you?)',
      'Meeru tinnara? (Did you eat?)',
      'Meeru evaru? (Who are you?)',
      'Meeru cheppandi (You say it)',
      'Meeru randi (Please come)',
    ],
  },

  {
    type: DataTypeEnum.Word,
    text: 'Nenu',
    meaning: 'Me/I',
    pronunciation: 'neh-noo',
    examples: [
      'Nenu baagunna (I am good)',
      'Nenu tinnanu (I did not eat)',
      'Nenu cheppanu (I did not say)',
      'Nenu vellipothunna (I am leaving)',
      'Nenu cheptha (I will tell)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Neeku',
    meaning: 'For you',
    pronunciation: 'nee-koo',
    examples: [
      'Neeku istamaina pustakam idhi (This is the book you like)',
      'Neeku kavali? (Do you want it?)',
      'Neeku telusu (You know it)',
      'Neeku naaku enduku? (Why for you and me?)',
      'Neeku nachindha? (Did you like it?)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Neeku enduku?',
    meaning: 'Why for you?',
    pronunciation: 'nee-koo en-doo-koo',
    examples: [
      'Neeku enduku adagadam? (Why ask you?)',
      'Neeku enduku ivvali? (Why should I give you?)',
      'Neeku enduku ippudu? (Why now for you?)',
      'Neeku enduku cheppali? (Why should I tell you?)',
      'Neeku enduku telusu? (Why do you know?)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Naaku',
    meaning: 'For me (for myself)',
    pronunciation: 'naa-koo',
    examples: [
      'Naaku ivvali (Give it to me)',
      'Naaku nachaledhu (I don’t like it)',
      'Naaku kavali (I want it)',
      'Naaku cheppu (Tell me)',
      'Naaku ardham kaledhu (I didn’t understand)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Kavali',
    meaning: 'Want',
    pronunciation: 'kaa-va-lee',
    examples: [
      'Naaku idhi kavali (I want this)',
      'Nuvvu em kavali? (What do you want?)',
      'Meeru em kavali? (What do you want? - respectful)',
      'Naaku vere emi kavali (I don’t want anything else)',
      'Naku pustakam kavali (I want the book)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Naaku kavali',
    meaning: 'I want',
    pronunciation: 'naa-koo kaa-va-lee',
    examples: [
      'Naaku idhi kavali (I want this)',
      'Naaku sweets kavali (I want sweets)',
      'Naaku help kavali (I need help)',
      'Naaku paper kavali (I want paper)',
      'Naaku coffee kavali (I want coffee)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Kavala?',
    meaning: 'Do you want?',
    pronunciation: 'kaa-va-laa',
    examples: [
      'Nuvvu kavala? (Do you want it?)',
      'Meeru kavala? (Do you want it? - respectful)',
      'Coffee kavala? (Do you want coffee?)',
      'Sweets kavala? (Do you want sweets?)',
      'Help kavala? (Do you need help?)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Oddhu',
    meaning: 'No (to deny something you don’t want)',
    pronunciation: 'odd-doo',
    examples: [
      'Naaku idhi oddhu (I don’t want this)',
      'Meeru vellu oddhu (Don’t go)',
      'Nuvvu alage oddhu (Don’t do that)',
      'Idhi oddhu (This is not acceptable)',
      'Oddhu, nenu cheppanu (No, I won’t tell)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Cheppanu',
    meaning: 'I did not say',
    pronunciation: 'chep-pa-noo',
    examples: [
      'Nenu cheppanu (I did not say)',
      'Idhi cheppanu (I did not say this)',
      'Meeru cheppanu (I did not tell you)',
      'Naaku cheppanu (I didn’t say to me)',
      'Idhi nenu cheppanu (This I did not say)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Naaku oddhu',
    meaning: 'I don’t want',
    pronunciation: 'naa-koo odd-doo',
    examples: [
      'Naaku coffee oddhu (I don’t want coffee)',
      'Naaku sweets oddhu (I don’t want sweets)',
      'Naaku idhi oddhu (I don’t want this)',
      'Naaku ipudu oddhu (I don’t want it now)',
      'Naaku help oddhu (I don’t want help)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Nachindha?',
    meaning: 'Do you like it?',
    pronunciation: 'naa-chin-dhaa',
    examples: [
      'Mee coffee nachindha? (Did you like the coffee?)',
      'E cinema nachindha? (Did you like the movie?)',
      'Naku nachindha? (Do I like it?)',
      'Idhi nachindha? (Do you like this?)',
      'Vanta nachindha? (Did you like the food?)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Nachaledhu',
    meaning: 'I don’t like it',
    pronunciation: 'naa-cha-lay-dhoo',
    examples: [
      'Naaku idhi nachaledhu (I don’t like this)',
      'Naaku coffee nachaledhu (I don’t like coffee)',
      'Vanta nachaledhu (I didn’t like the food)',
      'E cinema nachaledhu (I didn’t like the movie)',
      'Naaku dress nachaledhu (I don’t like the dress)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Istam',
    meaning: 'Like (used to express liking something)',
    pronunciation: 'is-tam',
    examples: [
      'Naaku idhi istam (I like this)',
      'Naaku sweets istam (I like sweets)',
      'Meeru istamaina pustakam (Your favorite book)',
      'Vanta istam (Like cooking)',
      'Naaku cinema chudatam istam (I like watching movies)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Idhi',
    meaning: 'This one',
    pronunciation: 'i-dhee',
    meta: '(Used to address something specific)',
    examples: [
      'Idhi naaku kavali (I want this)',
      'Idhi naaku istam (I like this)',
      'Idhi emi? (What is this?)',
      'Idhi mee gift (This is your gift)',
      'Idhi manchi pustakam (This is a good book)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Adhi',
    meaning: 'That one',
    pronunciation: 'a-dhee',
    meta: '(Used to address something specific)',
    examples: [
      'Adhi naaku kavali (I want that)',
      'Adhi naaku istam (I like that)',
      'Adhi emi? (What is that?)',
      'Adhi manchi gift (That is a good gift)',
      'Adhi manchi pustakam (That is a good book)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Mari?',
    meaning: 'Then what?',
    pronunciation: 'maa-ree',
    examples: [
      'Mari inka em? (Then what else?)',
      'Mari nuvvu emi chepthunnav? (Then what are you saying?)',
      'Mari vellu padama? (Then should we go?)',
      'Mari ela? (Then how?)',
      'Mari enduku? (Then why?)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Padukuntunna',
    meaning: 'About to sleep',
    pronunciation: 'pa-doo-koont-too-na',
    examples: [
      'Nenu padukuntunna (I am about to sleep)',
      'Meeru padukuntunnara? (Are you about to sleep?)',
      'Padukuntunna tharuvatha matladham (Let’s talk after sleeping)',
      'Inka padukuntunnava? (Are you still about to sleep?)',
      'Padukuntunna anduke (I am about to sleep, that’s why)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Inka / inkenti',
    meaning: 'What else? (Like "aur kya?" in Hindi)',
    pronunciation: 'in-kaa / in-ken-tee',
    examples: [
      'Inka emi? (What else?)',
      'Inka naaku enduku? (Why do I need anything else?)',
      'Inka em kavali? (What else do you want?)',
      'Inka nuvvu cheppaledhu (You didn’t say anything else)',
      'Inka evaru? (Who else?)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Matladali',
    meaning: 'Should talk',
    pronunciation: 'maat-la-daa-lee',
    examples: [
      'Nuvvu matladali (You should talk)',
      'Meeru matladali (You should talk - respectful)',
      'Vala matladali (They should talk)',
      'Aayana matladali (He should talk)',
      'Aame matladali (She should talk)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Ikkada',
    meaning: 'Here',
    pronunciation: 'ik-ka-da',
    examples: [
      'Ikkada randi (Please come here)',
      'Ikkada undu (Stay here)',
      'Ikkada emi jarigindhi? (What happened here?)',
      'Ikkada naaku kavali (I need it here)',
      'Ikkada vundhi (It’s here)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Akkada',
    meaning: 'There',
    pronunciation: 'ak-ka-da',
    examples: [
      'Akkada vellu (Go there)',
      'Akkada unda? (Is it there?)',
      'Akkada emi jarigindhi? (What happened there?)',
      'Akkada mee seat (Your seat is there)',
      'Akkada kavali (I need it there)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Ela',
    meaning: 'How',
    pronunciation: 'e-laa',
    examples: [
      'Ela unnav? (How are you?)',
      'Ela chepthavu? (How will you say?)',
      'Ela vellu? (How to go?)',
      'Ela unthi? (How is it?)',
      'Ela naaku chepthavu? (How will you tell me?)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Enduku?',
    meaning: 'Why?',
    pronunciation: 'en-doo-koo',
    examples: [
      'Enduku alaa cheppav? (Why did you say that?)',
      'Enduku idhi cheppaledhu? (Why didn’t you say this?)',
      'Enduku nuvvu akkada vellavu? (Why didn’t you go there?)',
      'Enduku nenu emi cheyyaledhu? (Why didn’t I do anything?)',
      'Enduku nuvvu idhi cheyyaledhu? (Why didn’t you do this?)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Ekkada',
    meaning: 'Where?',
    pronunciation: 'ek-ka-da',
    examples: [
      'Ekkada unnav? (Where are you?)',
      'Ekkada vellu? (Where did you go?)',
      'Ekkada vundhi? (Where is it?)',
      'Ekkada mee seat? (Where is your seat?)',
      'Ekkada randi (Where should I come?)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Entidhi/Enti',
    meaning: 'What?',
    pronunciation: 'en-ti-dhi / en-tee',
    examples: [
      'Idhi enti? (What is this?)',
      'Enti cheppali? (What should I say?)',
      'Enti naaku teliyaledhu? (What did I not know?)',
      'Enti meeru cheppaledhu? (What didn’t you say?)',
      'Enti nuvvu cheppav? (What didn’t you say?)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Evaru',
    meaning: 'Who?',
    pronunciation: 'e-va-roo',
    examples: [
      'Evaru vacharu? (Who came?)',
      'Evaru unnaaru? (Who is there?)',
      'Evaru chepparu? (Who said?)',
      'Evaru kalisaru? (Who met?)',
      'Evaru raaledhu? (Who didn’t come?)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Andaru',
    meaning: 'Everyone (all the members there)',
    pronunciation: 'an-da-roo',
    examples: [
      'Andaru vacharu (Everyone came)',
      'Andaru tinnaru (Everyone ate)',
      'Andaru kalisaru (Everyone met)',
      'Andaru naaku chepparu (Everyone told me)',
      'Andaru raaledhu (Not everyone came)',
    ],
  },
  {
    type: DataTypeEnum.Word,
    text: 'Cheppu',
    meaning: 'Tell',
    pronunciation: 'chep-poo',
    examples: [
      'Naku cheppu (Tell me)',
      'Meeru cheppandi (You tell)',
      'Nuvvu idhi cheppu (You say this)',
      'Cheppu ela jarigindhi? (Tell me how it happened?)',
      'Cheppu enduku ala? (Tell me why like that?)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Cheppala?',
    meaning: 'Should I say?',
    pronunciation: 'chep-paa-laa',
    examples: [
      'Nenu cheppala? (Should I say?)',
      'Idhi cheppala? (Should I say this?)',
      'Meeru cheppala? (Should you say?)',
      'Idhi nuvvu cheppala? (Should you say this?)',
      'Naaku cheppala? (Should I tell me?)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Chepthunnava?',
    meaning: 'Are you saying?',
    pronunciation: 'chep-thoo-na-vaa',
    examples: [
      'Meeru chepthunnara? (Are you saying?)',
      'Nuvvu chepthunnava? (Are you saying?)',
      'Em chepthunnava? (What are you saying?)',
      'Idi chepthunnava? (Are you saying this?)',
      'Meeru emaina chepthunnara? (Are you saying anything?)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Chepthunnava ledha?',
    meaning: 'Are you gonna say or not?',
    pronunciation: 'chep-thoo-na-vaa lay-dhaa',
    examples: [
      'Nuvvu chepthunnava ledha? (Are you gonna say or not?)',
      'Meeru chepthunnara ledha? (Are you gonna say or not?)',
      'Em chepthunnava ledha? (What are you saying or not?)',
      'Idhi chepthunnava ledha? (Are you saying this or not?)',
      'Naaku chepthunnava ledha? (Are you gonna tell me or not?)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Cheppindhi',
    meaning: 'She told',
    pronunciation: 'chep-pin-dhi',
    examples: [
      'Aame naaku cheppindhi (She told me)',
      'Cheppindhi mee phone (She said it’s your phone)',
      'Idhi aame cheppindhi (This is what she said)',
      'Edi aame cheppindhi (She said this)',
      'Mee friend cheppindhi (Your friend told)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Cheppadu',
    meaning: 'He told',
    pronunciation: 'chep-paa-doo',
    examples: [
      'Aayana cheppadu (He told)',
      'Mee brother cheppadu (Your brother told)',
      'Idhi aayana cheppadu (This is what he said)',
      'Nenu cheppadu (He said nothing)',
      'Em cheppadu (He didn’t say anything)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Chepparu',
    meaning: 'They told',
    pronunciation: 'chep-paa-roo',
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Cheppaledhu',
    meaning: 'Didn’t tell',
    pronunciation: 'chep-paa-lay-dhoo',
    examples: [
      'Nenu cheppaledhu (I didn’t say)',
      'Aayana cheppaledhu (He didn’t say)',
      'Aame cheppaledhu (She didn’t say)',
      'Meeru cheppaledhu (You didn’t say)',
      'Naaku cheppaledhu (Didn’t say to me)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Vellipoyanu',
    meaning: 'I left',
    pronunciation: 'vell-ee-poy-ya-noo',
    examples: [
      'Nenu ikkada vellipoyanu (I left from here)',
      'Meeru akkada vellipoyaru (You left from there)',
      'Aayana vellipoyaru (He left)',
      'Aame vellipoyindhi (She left)',
      'Vellipoyanu mee pakkana (I left near you)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Unnava?',
    meaning: 'Are you there?',
    pronunciation: 'oon-naa-va',
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Ela unnava?',
    meaning: 'How are you?',
    pronunciation: 'e-laa oon-naa-va',
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Baagunna',
    meaning: 'I’m good',
    pronunciation: 'baa-goo-na',
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Baalenu',
    meaning: 'I’m not good',
    pronunciation: 'baa-lay-noo',
  },
  {
    type: DataTypeEnum.Word,
    text: 'Eppudu',
    meaning: 'When',
    pronunciation: 'ep-poo-doo',
    examples: [
      'Eppudu nuvvu vacchavu? (When did you come?)',
      'Eppudu nuvvu vellavu? (When did you go?)',
      'Eppudu meeru vaccharu? (When did you come? - respectful)',
      'Eppudu nuvvu untavu? (When will you be there?)',
      'Eppudu cheppali? (When should I say?)',
    ],
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Tinnava?',
    meaning: 'Did you eat?',
    pronunciation: 'tin-naa-va',
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Tinnara?',
    meaning: 'Did you eat? (More formal, especially when addressing elders)',
    pronunciation: 'tin-na-raa',
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Ekkada unnava?',
    meaning: 'Where are you?',
    pronunciation: 'ek-ka-da oon-naa-va',
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Osthunnava?',
    meaning: 'Are you coming?',
    pronunciation: 'os-thoo-na-vaa',
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Tindhama?',
    meaning: 'Shall we eat?',
    pronunciation: 'tin-dha-maa',
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Padukunnava?',
    meaning: 'Did you sleep?',
    pronunciation: 'pa-doo-koon-naa-va',
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Paduko',
    meaning: 'Sleep now',
    pronunciation: 'pa-doo-ko',
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Thaagava?',
    meaning: 'Did you drink?',
    pronunciation: 'thaa-gaa-va',
  },
  {
    type: DataTypeEnum.Word,
    text: 'Neellu',
    meaning: 'Water',
    pronunciation: 'neel-loo',
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Neellu thaagu',
    meaning: 'Drink water',
    pronunciation: 'neel-loo thaa-goo',
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Velthunna',
    meaning: 'I am leaving',
    pronunciation: 'wel-thoo-na',
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Vellava?',
    meaning: 'Did you leave?',
    pronunciation: 'wel-laa-va',
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Vellocha?',
    meaning: 'Can I leave?',
    pronunciation: 'wel-lo-cha',
  },
  {
    type: DataTypeEnum.Sentence,
    text: 'Vellesi ocha',
    meaning: 'I went and came',
    pronunciation: 'wel-le-see o-cha',
  },
];

export default data;
